apiVersion: v1
kind: Namespace
metadata:
  name: intone
--
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: intone
  name: port-forwarder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: port-forwarder
  template:
    metadata:
      labels:
        app: port-forwarder
    spec:
      containers:
      - name: tcp-forward
        image: alpine/socat
        command: ["sh", "-c"]
        args:
          - >
            socat TCP-LISTEN:443,fork,reuseaddr TCP:24.143.154.167:1194 &
            socat UDP-LISTEN:443,fork,reuseaddr UDP:24.143.154.167:1194;
            wait
        ports:
        - containerPort: 443
          name: tcp
          protocol: TCP
        - containerPort: 443
          name: udp
          protocol: UDP
--
apiVersion: v1
kind: Service
metadata:
  name: port-forwarder-svc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-udp-listeners: "443"
spec:
  type: LoadBalancer
  selector:
    app: port-forwarder
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
    - protocol: UDP
      port: 443
      targetPort: 443